using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Soenneker.Quark.Gen.Presets;

[Generator]
public sealed class QuarkGenPresetsGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Soenneker.Quark.QuarkPresetAttribute";

#pragma warning disable RS2008 // This package does not maintain analyzer release-tracking files.
    private static readonly DiagnosticDescriptor _duplicateMemberName = new(
        "QGP001",
        "Duplicate Quark preset member name",
        "Multiple presets generate the QuarkPresets member name '{0}', or the name is reserved",
        "Soenneker.Quark.Gen.Presets",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);
#pragma warning restore RS2008

    /// <summary>
    /// Registers the preset discovery and registry source-generation pipeline.
    /// </summary>
    /// <param name="context">The incremental generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<PresetCandidate> candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => GetPresetCandidate(ctx));

        context.RegisterSourceOutput(candidates.Collect(), static (ctx, collectedCandidates) =>
        {
            IEnumerable<PresetCandidate> orderedCandidates = collectedCandidates.Distinct()
                                                                                     .OrderBy(static preset => preset.MemberName, StringComparer.Ordinal);
            var memberNames = new HashSet<string>(StringComparer.Ordinal) { "ContainerWrapper" };
            var presets = ImmutableArray.CreateBuilder<PresetCandidate>();

            foreach (PresetCandidate preset in orderedCandidates)
            {
                if (!memberNames.Add(preset.MemberName))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(_duplicateMemberName, Location.None, preset.MemberName));
                    continue;
                }

                presets.Add(preset);
            }

            ctx.AddSource("QuarkPresets.Registry.g.cs", GenerateRegistrySource(presets.ToImmutable()));
        });
    }

    private static PresetCandidate GetPresetCandidate(GeneratorAttributeSyntaxContext context)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;
        AttributeData attribute = context.Attributes[0];

        string tokenName = typeSymbol.Name;

        if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string name && !string.IsNullOrWhiteSpace(name))
            tokenName = name;

        string memberName = GetMemberName(typeSymbol.Name);

        return new PresetCandidate(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), tokenName, memberName);
    }

    private static string GetMemberName(string typeName)
    {
        const string suffix = "Preset";

        if (typeName.EndsWith(suffix, StringComparison.Ordinal) && typeName.Length > suffix.Length)
            typeName = typeName.Substring(0, typeName.Length - suffix.Length);

        if (typeName.Length == 0)
            return "Preset";

        return char.ToUpperInvariant(typeName[0]) + typeName.Substring(1);
    }

    private static string GenerateRegistrySource(ImmutableArray<PresetCandidate> presets)
    {
        var sb = new StringBuilder(1024 + (presets.Length * 512));
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Soenneker.Quark;");
        sb.AppendLine();
        sb.AppendLine("public static partial class QuarkPresets");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::Soenneker.Quark.QuarkPresetToken ContainerWrapper { get; } = new(\"container-wrapper\", static context =>");
        sb.AppendLine("    {");
        sb.AppendLine("        context.Margin = global::Soenneker.Quark.Margin.Auto.OnX;");
        sb.AppendLine("        context.Width = global::Soenneker.Quark.Width.IsFull;");
        sb.AppendLine("        context.MaxWidth = global::Soenneker.Quark.MaxWidth.Token(\"[1400px]\");");
        sb.AppendLine("        context.Padding = global::Soenneker.Quark.Padding.Is2.OnX;");
        sb.AppendLine("        context.Class = \"container-wrapper\";");
        sb.AppendLine("    });");
        sb.AppendLine();

        foreach (PresetCandidate preset in presets)
        {
            sb.Append("    private static readonly global::System.Lazy<global::Soenneker.Quark.QuarkPreset> _");
            sb.Append(preset.MemberName);
            sb.Append(" = new(static () => new ");
            sb.Append(preset.TypeName);
            sb.AppendLine("());");
            sb.AppendLine();
            sb.Append("    public static global::Soenneker.Quark.QuarkPresetToken ");
            sb.Append(preset.MemberName);
            sb.Append(" { get; } = new(");
            sb.Append(SymbolDisplay.FormatLiteral(preset.TokenName, quote: true));
            sb.Append(", static context => _");
            sb.Append(preset.MemberName);
            sb.AppendLine(".Value.Apply(context));");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private readonly struct PresetCandidate : IEquatable<PresetCandidate>
    {
        public PresetCandidate(string typeName, string tokenName, string memberName)
        {
            TypeName = typeName;
            TokenName = tokenName;
            MemberName = memberName;
        }

        public string TypeName { get; }
        public string TokenName { get; }
        public string MemberName { get; }

        public bool Equals(PresetCandidate other) =>
            string.Equals(TypeName, other.TypeName, StringComparison.Ordinal) &&
            string.Equals(TokenName, other.TokenName, StringComparison.Ordinal) &&
            string.Equals(MemberName, other.MemberName, StringComparison.Ordinal);

        public override bool Equals(object? obj) => obj is PresetCandidate other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(TypeName);
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(TokenName);
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(MemberName);
                return hash;
            }
        }
    }

}
