using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Soenneker.Quark.Gen.Presets;

[Generator]
public sealed class QuarkGenPresetsGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Soenneker.Quark.QuarkPresetAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<PresetCandidate?> candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
            static (ctx, _) => GetPresetCandidate(ctx))
            .Where(static candidate => candidate is not null);

        context.RegisterSourceOutput(candidates.Collect(), static (ctx, candidates) =>
        {
            var presets = candidates.Where(static candidate => candidate is not null)
                                    .Select(static candidate => candidate!.Value)
                                    .Distinct()
                                    .OrderBy(static preset => preset.MemberName, StringComparer.Ordinal)
                                    .ToImmutableArray();

            ctx.AddSource("QuarkPresets.Registry.g.cs", GenerateRegistrySource(presets));
        });
    }

    private static PresetCandidate? GetPresetCandidate(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol typeSymbol)
            return null;

        AttributeData? attribute = null;

        foreach (AttributeData attr in typeSymbol.GetAttributes())
        {
            INamedTypeSymbol? attrClass = attr.AttributeClass;

            if (attrClass is null)
                continue;

            if (string.Equals(attrClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + AttributeMetadataName, StringComparison.Ordinal) ||
                string.Equals(attrClass.ToDisplayString(), AttributeMetadataName, StringComparison.Ordinal))
            {
                attribute = attr;
                break;
            }
        }

        if (attribute is null)
            return null;

        string tokenName = typeSymbol.Name;

        if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string name && !string.IsNullOrWhiteSpace(name))
            tokenName = name;

        string memberName = GetMemberName(typeSymbol.Name);

        return new PresetCandidate(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), tokenName, memberName);
    }

    private static string GetMemberName(string typeName)
    {
        const string suffix = "Preset";

        if (typeName.EndsWith(suffix, StringComparison.Ordinal) && typeName.Length > suffix.Length)
            typeName = typeName.Substring(0, typeName.Length - suffix.Length);

        if (typeName.Length == 0)
            return "Preset";

        return char.ToUpperInvariant(typeName[0]) + typeName.Substring(1);
    }

    private static string GenerateRegistrySource(ImmutableArray<PresetCandidate> presets)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Soenneker.Quark;");
        sb.AppendLine();
        sb.AppendLine("public static partial class QuarkPresets");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::Soenneker.Quark.QuarkPresetToken ContainerWrapper { get; } = new(\"container-wrapper\", static context =>");
        sb.AppendLine("    {");
        sb.AppendLine("        context.Margin = global::Soenneker.Quark.Margin.Auto.OnX;");
        sb.AppendLine("        context.Width = global::Soenneker.Quark.Width.IsFull;");
        sb.AppendLine("        context.MaxWidth = global::Soenneker.Quark.MaxWidth.Token(\"[1400px]\");");
        sb.AppendLine("        context.Padding = global::Soenneker.Quark.Padding.Is2.OnX;");
        sb.AppendLine("        context.Class = \"container-wrapper\";");
        sb.AppendLine("    });");
        sb.AppendLine();

        foreach (PresetCandidate preset in presets)
        {
            sb.Append("    private static readonly global::System.Lazy<global::Soenneker.Quark.QuarkPreset> _");
            sb.Append(preset.MemberName);
            sb.Append(" = new(static () => new ");
            sb.Append(preset.TypeName);
            sb.AppendLine("());");
            sb.AppendLine();
            sb.Append("    public static global::Soenneker.Quark.QuarkPresetToken ");
            sb.Append(preset.MemberName);
            sb.Append(" { get; } = new(\"");
            sb.Append(Escape(preset.TokenName));
            sb.Append("\", static context => _");
            sb.Append(preset.MemberName);
            sb.AppendLine(".Value.Apply(context));");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private readonly struct PresetCandidate : IEquatable<PresetCandidate>
    {
        public PresetCandidate(string typeName, string tokenName, string memberName)
        {
            TypeName = typeName;
            TokenName = tokenName;
            MemberName = memberName;
        }

        public string TypeName { get; }
        public string TokenName { get; }
        public string MemberName { get; }

        public bool Equals(PresetCandidate other) =>
            string.Equals(TypeName, other.TypeName, StringComparison.Ordinal) &&
            string.Equals(TokenName, other.TokenName, StringComparison.Ordinal) &&
            string.Equals(MemberName, other.MemberName, StringComparison.Ordinal);

        public override bool Equals(object? obj) => obj is PresetCandidate other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(TypeName);
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(TokenName);
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(MemberName);
                return hash;
            }
        }
    }

}
