using Microsoft.CodeAnalysis;
using System.Text;

namespace Soenneker.Quark.Gen.Presets;

[Generator]
public sealed class QuarkGenPresetsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace Soenneker.Quark.Gen.Presets.Generated;");
            sb.AppendLine();
            sb.AppendLine("public static partial class GeneratedMarker");
            sb.AppendLine("{");
            sb.AppendLine("    public const string Name = \"Soenneker.Quark.Gen.Presets\";");
            sb.AppendLine("}");
            ctx.AddSource("Generated.g.cs", sb.ToString());
        });
    }
}
